### ISSUE TITLE
Graph connector Agent

### ISSUE THREAD

**Issue by Jiannko** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#160]
After installing and configuring the Graph connector agent as per the below link
https://docs.microsoft.com/en-us/microsoftsearch/on-prem-agent

I am unable to register  at the end  the Error message is "Something went wrong .Please click on the register again to retry."

Screen shot attached
<img width="576" alt="GCA" src="https://user-images.githubusercontent.com/30264405/118030791-09f4b400-b366-11eb-9697-e2f0e52a9303.png">

I am using 'Client secrets'  in Authentication. 

Error from log 

2021-05-12 21:40:45,038 [1] ERROR - {ErrorCode=ConfigAppRegistrationFailure, ErrorMessage=Registration failed}
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)

Any ideas!

**Comment by mecampos** [comment]
Hello @Jiannko, please send an email with these details to MicrosoftGraphConnectorsFeedback@service.microsoft.com, referencing this issue and also include the tenant ID where this is happening.

**Comment by Jiannko** [comment]
> Hello @Jiannko, please send an email with these details to [MicrosoftGraphConnectorsFeedback@service.microsoft.com](mailto:MicrosoftGraphConnectorsFeedback@service.microsoft.com), referencing this issue and also include the tenant ID where this is happening.

Details sent .

**Comment by Jiannko** [comment]
The  error i mentioned has gone after the APIs were granted Admin consent . But I fail when adding the connector
'**Graph connector agent associated with the connection is not reachable.**'
The agent application is running . Its configured with a Search Admin.
And the secret hasnt expired.
Any other areas which i should be checking!
